import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

const rendererRoot = path.resolve(process.cwd());
const repoRoot = path.resolve(rendererRoot, '..');
const args = parseArgs(process.argv.slice(2));

if (args.help || !args.project) {
  printHelp();
  process.exit(args.help ? 0 : 1);
}

const input = path.resolve(rendererRoot, args.project);
if (!fs.existsSync(input) || !fs.statSync(input).isFile()) fail(`Render-Manifest nicht gefunden: ${input}`);
const manifest = readJson(input);
validateManifest(manifest);

const publicAssets = path.join(rendererRoot, 'public', 'assets');
const publicAudio = path.join(rendererRoot, 'public', 'audio');
fs.rmSync(publicAssets, { recursive: true, force: true });
fs.rmSync(publicAudio, { recursive: true, force: true });
fs.mkdirSync(publicAssets, { recursive: true });
fs.mkdirSync(publicAudio, { recursive: true });

const prepared = structuredClone(manifest);
for (const [index, scene] of prepared.scenes.entries()) {
  const source = scene.asset?.source;
  if (!source) fail(`${scene.id || `scene-${index + 1}`}: Asset-Quelle fehlt.`);
  const safeId = safeName(scene.asset.id || `asset-${index + 1}`);
  if (!/^https?:\/\//i.test(source)) {
    const sourceFile = safeRepoFile(source, `${scene.id}: Quelle`);
    const extension = path.extname(sourceFile).toLowerCase();
    const targetName = `${String(index + 1).padStart(3, '0')}-${safeId}${extension}`;
    fs.copyFileSync(sourceFile, path.join(publicAssets, targetName));
    scene.asset.source = `assets/${targetName}`;
  }

  const preview = scene.asset?.preview;
  if (preview && !/^https?:\/\//i.test(preview)) {
    const previewFile = safeRepoFile(preview, `${scene.id}: Preview`);
    const extension = path.extname(previewFile).toLowerCase() || '.jpg';
    const targetName = `${String(index + 1).padStart(3, '0')}-${safeId}-preview${extension}`;
    fs.copyFileSync(previewFile, path.join(publicAssets, targetName));
    scene.asset.preview = `assets/${targetName}`;
  }
}

if (prepared.voiceover) {
  if (prepared.voiceover.sourceType !== 'user-provided') fail('Workflow-v2-Voiceover muss vom Nutzer stammen.');
  if (prepared.voiceover.generatedByPipeline === true) fail('Automatisch erzeugte Ersatzstimmen sind nicht erlaubt.');
  const source = prepared.voiceover.source;
  if (!source) fail('Voiceover-Quelle fehlt.');
  if (/^https?:\/\//i.test(source)) fail('Workflow-v2-Voiceover muss als lokale, überprüfbare Projektdatei vorliegen.');
  const sourceFile = safeRepoFile(source, 'Voiceover');
  const extension = path.extname(sourceFile).toLowerCase();
  const targetName = `voiceover-master${extension}`;
  fs.copyFileSync(sourceFile, path.join(publicAudio, targetName));
  prepared.voiceover.source = `audio/${targetName}`;
}

const generated = path.join(rendererRoot, 'src', 'generated-manifest.ts');
fs.mkdirSync(path.dirname(generated), { recursive: true });
fs.writeFileSync(generated, `// Generated by renderer/scripts/prepare-project.mjs\nexport const generatedManifest = ${JSON.stringify(prepared, null, 2)} as const;\n`);

const generatedDir = path.join(rendererRoot, 'generated');
fs.mkdirSync(generatedDir, { recursive: true });
fs.writeFileSync(path.join(generatedDir, 'attribution.txt'), attributionText(prepared));
fs.writeFileSync(path.join(generatedDir, 'source-manifest.json'), `${JSON.stringify(prepared, null, 2)}\n`);

console.log(`Renderer vorbereitet: ${prepared.project.title}`);
console.log(`${prepared.scenes.length} Szenen · ${prepared.project.totalDurationSeconds}s · ${prepared.project.totalFrames} Frames`);
if (prepared.voiceover) console.log(`Master-Audio: ${prepared.voiceover.source} (${prepared.voiceover.durationSeconds}s)`);
console.log(`Attribution: generated/attribution.txt`);

function validateManifest(value) {
  if (!value || typeof value !== 'object') fail('Manifest muss ein Objekt sein.');
  const project = value.project;
  if (!project || !Number.isInteger(project.width) || !Number.isInteger(project.height) || !Number.isInteger(project.fps) || !Number.isInteger(project.totalFrames)) {
    fail('Manifest enthält keine gültigen Projekt-/Frame-Daten.');
  }
  if (project.width < 1 || project.height < 1 || project.fps < 1 || project.totalFrames < 1) fail('Projektwerte müssen positiv sein.');
  if (!Array.isArray(value.scenes) || value.scenes.length === 0) fail('Manifest enthält keine Szenen.');
  for (const scene of value.scenes) {
    if (!Number.isInteger(scene.fromFrame) || scene.fromFrame < 0) fail(`${scene.id}: fromFrame ungültig.`);
    if (!Number.isInteger(scene.durationInFrames) || scene.durationInFrames < 1) fail(`${scene.id}: durationInFrames ungültig.`);
    if (!scene.asset?.id || !scene.asset?.type || !scene.asset?.source) fail(`${scene.id}: Asset-Daten unvollständig.`);
    if (scene.presentation && !['auto','vertical-blur','contain','article','document','map','freeze-frame','headline'].includes(scene.presentation)) fail(`${scene.id}: presentation ungültig.`);
    if (scene.transition && !['cut','fade'].includes(scene.transition)) fail(`${scene.id}: transition ungültig.`);
  }
  if (project.workflowVersion === 2) {
    if (!value.voiceover?.source) fail('Workflow v2 verlangt eine Voiceover-Quelle im Manifest.');
    if (value.voiceover.sourceType !== 'user-provided') fail('Workflow v2 verlangt eine vom Nutzer gelieferte Voiceover-Datei.');
    if (value.voiceover.generatedByPipeline === true) fail('Workflow v2 verbietet Pipeline-generierte Ersatzstimmen.');
  }
}

function safeRepoFile(source, label) {
  const sourceFile = path.resolve(repoRoot, source);
  const repoPrefix = `${repoRoot}${path.sep}`;
  if (!sourceFile.startsWith(repoPrefix)) fail(`${label} liegt außerhalb des Repositories.`);
  if (!fs.existsSync(sourceFile) || !fs.statSync(sourceFile).isFile()) fail(`${label} fehlt: ${source}`);
  return sourceFile;
}
function attributionText(value) {
  const lines = (value.attribution || []).map((item) => {
    const urls = [item.sourceUrl, item.licenseUrl].filter(Boolean).join(' | ');
    return `- ${item.assetId}: ${item.text || 'Attribution erforderlich'}${urls ? ` | ${urls}` : ''}`;
  });
  return lines.length ? `Attributionen für ${value.project.title}\n\n${lines.join('\n')}\n` : `Keine verpflichtenden Attributionen für ${value.project.title}.\n`;
}
function parseArgs(values) {
  const result = {};
  for (let i = 0; i < values.length; i++) {
    const token = values[i];
    if (!token.startsWith('--')) fail(`Unbekanntes Argument: ${token}`);
    const key = token.slice(2).replace(/-([a-z])/g, (_, c) => c.toUpperCase());
    if (key === 'help') { result.help = true; continue; }
    const next = values[i + 1];
    if (!next || next.startsWith('--')) fail(`Wert für ${token} fehlt.`);
    result[key] = next;
    i++;
  }
  return result;
}
function readJson(file) { try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch (error) { fail(`JSON konnte nicht gelesen werden: ${error.message}`); } }
function safeName(value) { return String(value).toLowerCase().replace(/[^a-z0-9_-]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 80) || 'asset'; }
function fail(message) { console.error(message); process.exit(1); }
function printHelp() {
  console.log(`Visual Asset Hub Remotion Prepare\n\nIm renderer/-Ordner ausführen:\n  npm run prepare:project -- --project ../projects/erstes-video/render-manifest.json\n\nDer Befehl kopiert geprüfte lokale Assets, vorhandene Preview-/Freeze-Frames und – bei Workflow v2 – ausschließlich die vom Nutzer gelieferte Voiceover-Datei nach renderer/public/.`);
}
